isubit/iastate_theme

css/theme.css, templates/blocks/block--system-menu-block.html.twig, templates/blocks/block.html.twig
A new template for system menu blocks allows me to add our block
classes to that special block type.
=> D8ISUTHEME-36 Make block titles smaller

css/base.css, css/theme.css, templates/components/status-messages.html.twig, templates/forms/input--search.html.twig, templates/navigation/menu-local-tasks.html.twig
When the base theme is set up as the admin theme, a bunch of UI and forms styling issues popped up.
=> D8ISUTHEME 38 UI and Forms fixes

css/theme.css
More fixes to the UI and form work.
=> D8ISUTHEME 38

templates/layout/html.html.twig
Adds some helpful classes to the body.
=> D8-324 Adds helpful classes to the body tag

templates/layout/html.html.twig
Removed an extra h1 that was hanging out in html.html.twig and causing an unsightly gap at the top of pages.
=> D8ISUTHEME-51

css/base.css
Accessibility fix for Pagination items. The color contrast was too low.
=> D8ISUTHEME-58

css/theme.css
Adjusted the flex property to fix an issue in IE11 where the header elements were stacking on mobile.
=> D8ISUTHEME-54

css/base.css, templates/navigation/pager.html.twig, templates/navigation/views-mini-pager.html.twig
Two quick pagination accessibility fixes.
=> D8 isutheme 61

templates/parts/isu-navbar.html.twig
I have checked the links in the ISU Navbar against what we have in Suitcase_Interim. Can someone confirm they are all correct?
=> D8ISUTHEME-74 Update the links in the black ISU Navbar.

css/theme.css
To test
- pull down a copy of this branch
- make menu links from existing nodes on a site
- go to the node. is the menu item a different color?
=> D8-631 Add styling for active menu item

css/isu-social.css
* Prune the social media icons available, 
* decrease icon size, 
* add a generic icon for non-covered links
=> D8-718 Social media icons

css/theme.css, js/iastate_theme.js, templates/parts/site-navbar.html.twig
Allow the search button to be keyboard navigable on narrow widths.
=> D8-780 Allow the menu and search icons to be keyboard navigable

css/theme.css
This will also more closely match the central ISU website's menu color scheme.
=> D8-1142 Adjust menu background colors to improve web color accessibility

css/isu-social.css, iastate_theme.libraries.yml
To test: 
1. Add social media links to Google Scholar and Research Gate to both the footer and a People Profile (sites.iastate.edu project)
2. Do the icons show up? It should not be the general link  icon.
=> D8-1086 Add support for Research Gate and Google Scholar social icons

css/base.css, css/theme.css
We were finding that the default Bootstrap 4 headings and spacing wasn't quite right for content on our Drupal 8 platform, so we're adjusting it. 
When testing, pay attention to the heading sizes and spacing around headings and page titles. Does it look good to you? From a CSS perspective, this is a pretty simple page, but could touch many elements.
**To test:** 
1. Create a D8 site and use this branch of the theme.
2. Work in WYSIWYG editors to make pages with headings. It might help to copy actual pages so we can see if it works with real content. 
3. Add titles to homepage blocks
4. Fully fill out a people profile
5. Use the Blog, News, and Projects feature. On the list views, does the title size and spacing look right?
6. Look through the Site Settings pages. Anything funky with …
=> D8-1558 Revise typography

css/base.css
To test
1. Add an image to a page or something with CKeditor
2. Select the image, then click the link icon in the toolbar to make it a link.
3. Publish the page/node/block
4. Hover over the image - confirm there's a blue outline glow thing
=> D8ISUTHEME-115 Give images in links a hover state.

config/schema/iastate_theme.schema.yml
To test:
- Build a new site, add the iastate_theme and get this branch
- Run `composer require drupal/config_inspector`
- Install config inspector
- Go to `/admin/reports/config-inspector` and search for `iastate_theme.settings`. Do you see any errors? You shouldn't.
=> D8-1992 Update schema.yml with new settings

iastate_theme.theme
This PR adds a node id class to the `<body>` 
To test:
1. Create a site using this base theme and make some notes
2. Inspect the HTML when you are on a node and confirm there's a class like `node-id_5` on `<body>`
=> D8ISUTHEME-125

templates/parts/footer.html.twig
Inspect the HTML in the footer to ensure the typo got fixed.
=> D8ISUTHEME-138 Fix typo in footer

css/theme.css
Create enough content so that a View produces pagination. Confirm the pagination is centered. This should work with either the mini-pager or full pager.
=> D8ISUTHEME-145 Center pagination

iastate_theme.info.yml
Create a site with this version of the theme and ensure the theme is still looking right. I poked around creating some nodes, checking around Block Layout, and the Appearance settings.
=> D8ISUTHEME-148 Declare base theme

config/install/iastate_theme.settings.yml, config/schema/iastate_theme.schema.yml, theme-settings.php
To test:
- Build a new plain Drupal 9 site with `newd9plain.sh` and then check out this branch using `composer require isubit/iastate_theme:dev-D8ISUTHEME-161`
- Run `composer require drupal/config_inspector` and install the Configuration Inspector module
- Go to `/admin/reports/config-inspector/iastate_theme.settings/list` and verify that there are no missing schema errors
- Check out `/admin/appearance/settings/iastate_theme` to verify that the default settings are what you would expect
=> D8ISUTHEME-161 Update schema.yml

iastate_theme.theme
To test this, basically just make sure nothing is super broken after getting this branch. If something isn't right here, your site will probably break.
=> D8ISUTHEME-162 Move dependency to top of file

css/base.css, css/theme.css, iastate_theme.info.yml, templates/parts/site-navbar.html.twig
There are only two small changes to re-test:
1. Adjust header padding on mobile - https://github.com/isubit/iastate_theme/pull/179
2. Fix video overlap bug in CKEditor - https://github.com/isubit/iastate_theme/pull/180
=> Development - 1.7.1

css/base.css, css/isu-responsivetables.css, iastate_theme.info.yml
There is only one change in this release, to revert the majority of the table change from 1.7.5. To test, confirm the table changes detailed here stuck: https://github.com/isubit/iastate_theme/pull/198
=> Development 1.7.7
