css/theme.css
=> D8ISUTHEME-50 Fix Image Alignment radio inputs to be inline with label

css/theme.css, logo.svg
IE11 doesn't respect the aspect ratio of SVG that are shown via the img tag. I needed to beef up the ISU logo svg by setting height and width manually, and adding setting for aspect ratios. 
The CSS needed an adjustment as well. 
This shouldn't break things if someone subthemes with an image file.
=> D8-325 Fix ISU logo svg scaling for IE11

css/isu-navbar.css
The background of the Index alphabet dropdown was not spanning the full width of the list. IE11 requires an explicit min-width.
=> D8ISUTHEME-56 Fix the Index alphabet dropdown background width for IE11

css/theme.css
If the logo is taller than the basic ISU wordmark, the site name was hitting the bottom edge of the read header. Added a small margin-bottom.
=> D8ISUTHEME-45 Add space below the site name.

css/base.css
img height: auto !important was catching a spacer png in the CKEditor media embed.
=> D8ISUTHEME-67 Remove !important for image height

config/install/iastate_theme.settings.yml, iastate_theme.theme, templates/parts/footer.html.twig, theme-settings.php
This should allow site-builders to use a path for the footer logo, instead of it being hard-coded. No image upload yet.
=> D8ISUTHEME-68 Add footer logo as a theme setting.

css/theme.css
Ensure the unpublished tab sticks to the article even when Contextual Links is not active.
* Tested with an unpublished node when Contextual Links was both on and off.
=> D8ISUTHEME-69 Unpublished tab

css/theme.css
I expect the Edit Summary button on Textfields With Summaries (like most body fields) to be styled like a light outlined button without the parentheses.
=> D8ISUTHEME-71 Style Edit Summary button

templates/blocks/block--search-form-block.html.twig, templates/blocks/block--system-branding-block.html.twig, templates/blocks/block--system-menu-block.html.twig, templates/blocks/block.html.twig, templates/book/book-navigation.html.twig, templates/book/book-tree.html.twig, templates/components/status-messages.html.twig, templates/content/comment.html.twig, templates/content/node.html.twig, templates/fields/field--comment.html.twig, templates/fields/field--node--body.html.twig, templates/forums/node--forum.html.twig, templates/navigation/breadcrumb.html.twig, templates/navigation/links.html.twig, templates/navigation/menu-local-tasks.html.twig, templates/parts/footer.html.twig, templates/parts/menu-navbar.html.twig, templates/parts/submitted-by.html.twig, templates/search/item-list--search-results.html.twig, templates/search/search-result.html.twig
Big pull request. I went through all the base theme templates to see where we could improve the HTML/ARIA semantic elements. In many cases, I've switched to the strategy of wrapping self-contained content in `article` elements and starting any headings over at `h1`. More information about that:
- https://keithjgrant.com/posts/2018/03/html5-sectioning-and-landmark-elements/
- https://www.w3.org/WAI/GL/wiki/Using_HTML5_article_element
- https://www.w3.org/TR/2011/WD-html5-author-20110705/headings-and-sections.html#headings-and-sections
- https://www.w3.org/TR/2011/WD-html5-author-20110705/content-models.html#sectioning-content
Because CSS is not coupled to elements, there should be no visual changes.
=> D8ISUTHEME-77 Evaluating all theme templates to improve accesibility

css/theme.css
Right now the alignment of items in the second Header region is handled with margins and padding, but this sometimes creates extra gaps. Handling it with flexbox should make the space more flexible. 
To test: 
1. Make sure the search box is in Header Second. Does it look okay? Is it vertically centered?
2. Add the Site Links menu below it. (https://github.com/isubit/iastate_theme/wiki/Site-Navbar) How is the spacing now? Is it also nicely vertically centered without big gaps?
=> D8ISUTHEME-81 Fixed all the extra space around the header search bar

css/theme.css
1. In Drupal 8, the Delete buttons are actually links: https://www.drupal.org/node/2250341 So, at least for now, I'm styling them to appear as Bootstrap 4 `btn btn-outline-secondary` with CSS instead of using a function in .theme to apply the classes. 
2. There are also small adjustments to the spacing between labels and inputs to making spacing overall more consistent.
=> D8-609 Adjust form styles

iastate_theme.libraries.yml
The Snapchat icon wasn't showing up in the social media footer. Updating the library version fixed it.
=> D8ISUTHEME-83 Update FontAwesome library from 4.5 to 4.7

css/base.css, css/theme.css, iastate_theme.theme, templates/components/views-view-summary-unformatted.html.twig, templates/forms/input--submit.html.twig
We are working on a fairly significant revision to the button color strategy. The system's goals are to improve the contrast of button colors to conform better with WCAG, also to establish a system of what colors different types of buttons get. For example - red is now used in forms as DANGER, and the green SUCCESS color is our create/add actions. 
Button color changes will mostly affect node add and edit pages if that box is checked in the Appearance page. Most of the user facing buttons are still going to be outlined red to match the general branding.
=> D8-710 Changes to button colors

css/theme.css, templates/blocks/block--system-branding-block.html.twig
To test:
* Create a Drupal 8 site with this branch of the base theme
* The site name should now be smaller. 
* Fill in a site slogan. The site slogan should be small, and the site name large, and a line should separate.
This is the help more closely conform to ISU marketing standards which has clear requirements about what text can be part of an ISU wordmark.
=> D8-705 Add support for the site slogan

css/theme.css, iastate_theme.theme, templates/blocks/block--system-branding-block.html.twig, theme-settings.php
To test:
* Create a Drupal 8 site with this branch of the base theme
* Try adding a unit name, then a unit name and unit URL
* If there is a unit name, it should take the place of the site name directly beneath the Logo.
* If there is a unit url, the unit name should be a link. If there is no unit url, it should not be a link.
* The site name should link to the homepage.
=> D8-723 Add custom theme settings for the site unit and unit url

css/theme.css, iastate_theme.theme, templates/components/confirm-form.html.twig, templates/forms/input--submit.html.twig, templates/layout/html.html.twig
*Goal*
- The current delete page (`node/%/delete`) was difficult to read and had the wrong colors for the buttons, making it a little unclear as to the purpose of the buttons. I wanted to make the page more deliberate and easier to use.
*What I did*
- Created the template for the confirmation page to wrap the page text in an alert
- Updated the submit buttons template to apply the proper classes to delete buttons
- Added css to manually style the cancel button which is actually a link
- Added some additional useful classes to the body to tell whether you're on a node form page
*To test*
- Create a node, then try to delete it
- Does the delete page have the warning in a red alert box, a red delete button, and a grey-outlined cancel button?
- Can you keyboard navigate to the buttons?
- Does …
=> D8ISUTHEME-87 Redesign delete confirm page

css/base.css
The border around text inputs and other fields should now be darker to comply with WCAG 2.1's new standard.
=> D8-991 Increase contrast for form inputs for WCAG 2.1

css/theme.css
Autocomplete fields like tags, and select fields should now have bold labels.
=> D8-1005 Make more form field labels bold.

templates/forms/text-format-wrapper.html.twig
Help text added to formatted text areas was not getting the `isu-form-element-description` class because unlike other field types, the `description` is added to formatted text areas with the `text-format-wrapper.html.twig` file.
**To test:** 
Add help text to a formatted text field. Does it appear a smaller light grey like help text on other fields?
=> D8-1078 Styles help text on formatted text areas.

templates/parts/isu-navbar.html.twig
Do you see the Okta and Workday links in the Sign-ons dropdown? Do they go to the right place?
=> D8ISUTHEME-92 Add Okta and Workday links to Sign-Ons

css/base.css, js/isu-responsivetables.js
Right now tables with merged cells (colspan/rowspan) are not responsive. They should be horizontally scrollable without illegible smushing. That, and merged cells don't have enough borders to make sense. 
**To test:**
1. Make sure that your text formatter includes `<td rowspan colspan> <th rowspan colspan>`
2. Make some tables and merge cells both horizontally and vertically. 
3. When you publish the page, do the merged cells have nice borders that make sense?
4. When you narrow the screen, can you read the table with a horizontal scroll?
5. Go back and reverse the cell merging (I think you have to do the split commands). 
6. Publish. Does the table do the responsive thing moving content into a column?
=> D8ISUTHEME-93 Making colspan/rowspan tables responsive and properly styled.

templates/blocks/block.html.twig
We don't reliably have the ability to wrap blocks in `article` tags, so it's a safer bet to use `h2`.
=> D8-1394 Make block titles h2

css/base.css
To test: when making tables in CKEditor do the tables no longer stretch out full width? For our D8 platform, do the Basic and Striped styles also stop stretching in the editor?
They should already not be stretching on published pages.
=> Stop tables from stretching to full width in CKEditor

templates/book/book-navigation.html.twig
Book navigation (called Links in Manage Display) was running into fields placed above it. Added some margin to the book navigation template.
=> D8ISUTHEME-90 Add space above book navigation

templates/parts/site-navbar.html.twig
Small accessibility improvement.
There is a button element to open the search bar on narrow screens. The text just says 'Search' but that's the same text as the Search submit button, and that's not actually what it's doing. The button opens the search box. So that's what it says now.
This text is visually hidden so there won't be a visual change. But you can inspect the HTML to see the change.
=> D8ISUTHEME-98

templates/forms/input--video.html.twig
Drupal 8 has a video field where a url to a video on Vimeo or YouTube can be entered. Drupal 8 treats this as a separate field than a text or url field, so it was accidentally left unstyled. This branch adds a template to make sure it's properly styled. 
To test: 
1. Add a Video Embed field to a content type or custom block or something.
2. The style of the field on the form should look the same as a text field. Border, rounded corners and comfortable padding.
=> D8ISUTHEME-99 Add template for video fields

config/install/iastate_theme.settings.yml, css/theme.css, iastate_theme.theme, templates/parts/site-navbar.html.twig, theme-settings.php
This branch makes a theme setting to show/hide the gold border below the red Site Navbar. 
To test:
1. Create a site using this theme (not our subtheme)
2. The gold bar should be there.
3. Go to theme settings
4. Is there a checkbox for the gold border in the Site Navbar section at the top? Hope so.
5. It should be checked by default.
6. Uncheck it and save
7. The gold bar should disappear
=> D8ISUTHEME-103

templates/layout/page.html.twig
Right now if a block exists in a theme region (say a View block) and it has no content (say you checked the option to hide if empty), the theme region still renders, leaving a gap. This pull request makes sure the sidebars are hidden if they are empty. 
**To test:**
1. Make a plain D8 site (not the iastate8 platform) and set this theme as default.
2. Create some kind of throw-away View block, something to show some content.
3. Under the View's advanced options, choose Hide if empty.
4. Place the block in a sidebar (remove any other blocks that might be in the sidebar of choice)
Confirm the sidebar and block shows up if the View has content.
Confirm the sidebar doesn't show up if the View is empty.
=> D8ISUTHEME-106 Only show sidebars if blocks have content

css/theme.css, templates/forms/fieldset.html.twig
We are moving fieldset descriptions to the top so that it won't be buried under all the fields.
=> D8-1693 Move fieldset descriptions to the top

css/base.css
Our UIs for adding images as fields or in CKEditor could use some improvement. This branch affects two things: 
1. When there is an image field. It adds a little spacing and moves the alternative text field to the next line.
2. When adding an image via CKeditor. Mostly, aligning the alignment options in a row instead of a column. 
**To test:** 
1. Look at an image field and confirm it has the new design.
2. Add an image in CKeditor and confirm it has the new design.
Screenshots are in the last comment of the ticket: https://isubit.atlassian.net/browse/D8ISUTHEME-107
=> D8ISUTHEME-107 Improve UI for adding images.

css/base.css
**Hotfix**
1. Add/edit a Blog, Event, News, and Projects posts
2. Add a thumbnail image
3. Confirm the thumbnail preview isn't huge. Should be 200x120 (the image style that appears in a teaser)
=> D8ISUTHEME-110 Stop thumbnail preview sizing up

css/theme.css
To test...
1. Make sure that this base theme (or our subtheme) is being used for admin interfaces, like when you're logged in as a shib user
2. Go to the manage menu UI
3. Add a new link so you have access to the Operations dropbutton
4. Use the keyboard to use that dropdown. Both the main part and the dropdown arrow are separately focusable. 
Confirm you see a light blue inner shadow when you are focused on the Edit, Arrow, and Delete parts of the dropbutton.
=> D8ISUTHEME-112 Add focus states to dropbuttons

config/install/iastate_theme.settings.yml, iastate_theme.theme, templates/blocks/block--system-branding-block.html.twig, templates/parts/footer.html.twig, theme-settings.php
To test:
1. On a plain install of Drupal with just this base theme ...
2. Confirm the alt text on the header and footer logos are in place without changing anything
3. Go to the theme settings
4. Confirm there are now fields for the logo and footer logo
5. Test those fields by filing them out, saving, and confirming the alt text changed
=> Allow custom alt text for header and footer logos

config/install/iastate_theme.settings.yml, iastate_theme.theme, templates/parts/footer.html.twig, theme-settings.php
In the rare case we need to hide the copyright, here's a checkbox for that.
1. On a plain Drupal 8 site with this base theme
2. Confirm the copyright is still in place without changing anything
3. Go to the theme settings and check the new box to hide the copyright.
4. Save
5. Confirm the copyright is gone
=> Add theme setting to hide the copyright

css/base.css
By default Bootstrap 4 doesn't allow text in buttons to wrap. This has caused some problems with the the grid system if there is a button with long text. 
The way I tested this was to use a three column row in Layout Builder and put a very long link in a Text Card, then make it a button with the Style dropdown. 
Without this fix, the button will make it's column too big, throwing off the grid. With this fix, the button text will wrap.
=> D8ISUTHEME-126

css/theme.css
This PR adds more horizontal padding to main menu items. I think this helps distinguish the menu items especially when some have dropdown arrows or there are many items. 
The left and right padding should have increased from `0.5em` to `0.75em`
=> D8ISUTHEME-127 Increase horizontal padding of main menu items

templates/blocks/block--system-menu-block.html.twig, templates/book/book-navigation.html.twig, templates/book/book-tree.html.twig, templates/content-edit/filter-caption.html.twig, templates/layout/page.html.twig, templates/navigation/breadcrumb.html.twig, templates/navigation/pager.html.twig, templates/navigation/views-mini-pager.html.twig, templates/parts/footer.html.twig, templates/parts/site-navbar.html.twig, templates/parts/submitted-by.html.twig
From the ticket: 
_A WAI-ARIA attribute that has the exact same features as the HTML element it has been applied to has been used. The WAI-ARIA attribute is redundant since is doesn't provide the user with any additional information._
_For landmarks it has previously been a recommendation to use HTML5 and WAI-ARIA landmark roles together (e.g. WAI-ARIA role="navigation" on HTML5 'nav' elements) to maximize support, but with the widespread adoption of HTML5 this is no longer needed._
Here are the landmarks/roles I found and corrected:
1. header/banner
2. nav/navigation
3. aside/complementary
4. footer/content-info
5. figure/group
6. main/main
To test, I recommend double-checking my changes to ensure there are no typos.
=> D8ISUTHEME-135 Remove now redundant WAI-ARIA roles on landmarks.

css/theme.css, templates/forms/form-element.html.twig, templates/forms/input--number.html.twig
This covers the portion of the form styling updates from this ticket that pertain to default Drupal elements. (https://isubit.atlassian.net/browse/D8ISUTHEME-134)
**Things to test:**
- Is the number field label on a content type bold?
- Is the date field label on a content type bold?
- Does the actual number field get the nice Bootstrap 4 style?
- Do fieldsets within fieldsets get the fieldset styling?
See the screenshot in the ticket for those visuals.
**Things not to test:** 
- The error message HTML now includes some missing attributes. Just must have missed them. You can check out the commit to see what I mean.
=> D8ISUTHEME-134 Form styling fixes

css/theme.css, templates/forms/datetime-wrapper.html.twig
This branch does two things for a Date field
1. Uses the `label` element for the label
2. Makes the label bold.
To test:
Add a date field to a content type. Make sure not to use Date and Time.
=> D8ISUTHEME-137 Make date field labels bold

iastate_theme.theme, templates/layout/html.html.twig
https://isubit.atlassian.net/browse/D8ISUTHEME-128
The original but was that `node-type_` classes appeared on the `body` of pages that aren't nodes (like our temporary landing page or Views). 
This pull requests fixes that by moving the way the class is added from the template to a preprocess function that first checks if there even is a node type set. 
To test:
1. Make a D8 site with a couple nodes of different types and a view.
2. Confirm there is a `node-type_` class for nodes and that the machine name is filled in.
3. Confirm there is _not_ a `node-type_` class for non-nodes.
=> D8ISUTHEME-128 Remove node-type class from pages that aren't nodes

templates/parts/footer.html.twig
**To test:**
1. Go to Theme Settings
2. Add titles _only_ for each associate.
3. Save.
4. **Confirm** the affiliate titles appear below the footer. **Confirm** they are not links. (They should be spans.)
5. Go back to Theme Settings and add urls.
6. **Confirm** the affiliates are now correctly linked.
=> D8ISUTHEME-139 Allow footer associates not to have links.

css/base.css
https://isubit.atlassian.net/browse/D8ISUTHEME-142
Try in a couple of browsers, including Firefox where the issue was.
To test:
1. Create a page
2. In the WYSIWYG add a link and make it a button.
3. Confirm you click inside the button text to place your cursor in it.
4. Confirm you can use the arrow keys to move the cursor into the button text.
=> D8ISUTHEME-142 Override Bootstrap4's user-select on .btn

css/theme.css, templates/parts/footer.html.twig
https://isubit.atlassian.net/browse/D8ISUTHEME-147
This pull requests makes block titles in the footer smaller, bold, and dark grey. It applies to the default footer contact block, and `.isu-block-title` which is the class applied to Sites+ block types (Text Card, Link Card, etc). 
**To test**
1. Enter some contact information 
2. Create and place a Text Card, Link Card, or other Sites Card in any Footer region and set the block title to show.
3. Confirm the titles match the design in the ticket.
=> D8ISUTHEME-147 Make footer block titles smaller

css/theme.css
The background of the sign-off theme region in the footer is slightly darker than the actual footer, so the color contrast of text and other content elements was just a little too low. This PR boosts the contrast.
To test, I recommend creating a Text Card with text, links, buttons, quotes, etc and placing it in the footer. Then test the color contrast for legibility.
=> D8ISUTHEME-149 Adjust colors for contrast in sign-off footer region

templates/blocks/block--system-branding-block.html.twig
Drupal core has a field in basic site settings called "slogan". Our base theme should support it.
Build a plain D8 site and add this theme. Go to Configuration > Basic Site Settings and add a slogan.
The slogan should appear below the site name.
Note: Our subtheme has its own version of this template, so that will be a PR to the bitbucket repo.
=> D8ISUTHEME-150 Add support for slogan

templates/blocks/block--system-branding-block.html.twig
The theme settings UI allows you to uncheck "Use the logo supplied by the theme" and then not add any other options. Right now, if you do this and choose to have no logo, a broken image tag shows up. This pull request just removes the image tag when there is no logo.
1. Create a plain D8/D9 site
2. admin/appearance/settings/iastate8_theme
3. Test all three logo options:
a. Use the logo supplied by the theme
b. Upload a new logo
c. No logo
4. Confirm the logo appears or doesn't as expected, no empty or broken image tags.
=> D8ISUTHEME-154 Allow site logo to be optional.

css/isu-navbar.css, js/isu-navbar.js, templates/parts/isu-navbar.html.twig
A SiteImprove scan detected an incorrectly applied `aria-expanded` attribute on an unsupported element (`li`). It turns out, the ARIA attribute was not needed in those positions and were being used for the js interaction. This pull request, replaces the ARIA attribute with a `data-` attribute instead.
See the ticket for more details: https://isubit.atlassian.net/browse/D8ISUTHEME-156
To test:
1. Create a D8/D9 site
2. Ensure the black ISU Navbar functions with both mouse and keyboard interaction.
3. Check code for accessibility.
=> D8ISUTHEME-156 Remove incorrect aria-expanded attribute from ISU Navbar

config/install/iastate_theme.settings.yml, iastate_theme.theme, templates/blocks/block--system-branding-block.html.twig, theme-settings.php
There is now an option to make the site logo a link.
1. Create a plain D8 site and make this base theme the default theme.
2. Go to Appearance > Settings for this theme.
3. Find the new logo link setting in the logo section.
4. Give it a try.
=> D8ISUTHEME-158 Logo link theme setting

config/install/iastate_theme.settings.yml, css/base.css, css/theme.css, iastate_theme.theme, templates/blocks/block--system-branding-block.html.twig, templates/parts/footer.html.twig, theme-settings.php
Google's PageSpeed Insights suggests that images have an explicit width and height. The CMS handles this most of the time, but our theme logos need that set up. 
This pull request adds theme settings for the logo dimensions for both the header and footer logo.
- For both the header logo and footer logo, the default ones that are always there should just work. The HTML should have the correct explicit dimensions and there is no need to change the dimensions in theme settings.
- But if custom logos are going to be used, the dimensions need to be filled out.
- On narrow screens, the logos will become responsive regardless of the explicit dimensions.
- (In general, those using custom logos should upload logo images that are already resized.)
To test
1. Create a plain D8 site, add this theme, …
=> D8ISUTHEME-157 Header and footer logo dimensions

templates/parts/site-navbar.html.twig
Right now, the entire label for the mobile search button/toggle is being shown and it's not necessary. "Open Search Bar".
This pull request hides "Open" and "Bar" to all but screenreaders, making the label say "Search". 
**To test**
1. `newd8plain.sh D8ISUTHEME163`
2. Add this branch of the base theme and install and set default.
3. Search is automatically on.
4. Narrow the screen and confirm the word Search is below the magnifying glass icon.
5. Confirm it still works.
=> D8ISUTHEME-163 Shorten search toggle label to just Search

css/theme.css
Right now on narrow breakpoints, the site name is too close to the bottom of the red site header. This PR adjusts the padding on header elements for nicer spacing. 
**To test**
1. Create a D9 site with this branch of the base theme.
2. Narrow the screen and confirm that there is always sufficient padding between header elements and the bottom of the red header. 
3. Test with combinations of all wordmark elements, with and without: default logo, custom logo, long site name, slogan, and unit.
=> D8ISUTHEME-164 Adjust header padding

css/base.css, css/theme.css
Context: https://isubit.atlassian.net/browse/D8ISUTHEME-165 Basically, the image preview for embedded videos in CKEditor was secretly and silently too tall, invisibly covering up content that came after, preventing clicking in it.
To test
1. Create a site with this branch of the base theme
2. Embed a video in a Page and make sure you can add/edit text before and after the video
3. Upload an image to another page that's waaaay too wide, like more than 2000px wide.  Here's one: (http://placehold.it/2000x500). Confirm it scales to fit the editor.
4. Publish that page. Confirm it scales to fit the page.
4. Test the logo image dimensions to make sure they still function.
=> D8ISUTHEME-165 Move responsive image CSS rule to avoid issues in CKEditor

css/base.css
Responsive image CSS was causing images in table to squish if content in adjacent cells was big. This fix keeps table images their proper size.
1. To test, create a D9 site with this branch of the base theme. 
2. Make a page with a two column table.
3. In the first column, put an image with dimensions of like, 200 or 300px wide. 
4. In the second column, put in enough text that it would wrap to at least a second line.
5. Publish the page and confirm the image has not been squished.
=> D8ISUTHEME-175 Stop images in tables from squishing

css/isu-responsivetables.css
A recent change in our Sites+ platform includes a patch to allow content editors to resize table columns. This is great, but the inline CSS on table cells messes up alignment when the responsive tables kick in on mobile.
**To test**
1. Create a Sites+ site on the development branch and use this branch of the base theme.
2. Create a page and add a table with multiple columns
3. Resize some of the columns.
4. Narrow the screen until the responsive table kicks in and the table moves to a single column
5. Confirm all the rows are the correct width and not jagged and that everything is still readable.
=> D8ISUTHEME-177 Force table cell widths to 100% on mobile

iastate_theme.theme, templates/layout/html.html.twig
https://isubit.atlassian.net/browse/D8ISUTHEME-180
Right now there are several useful classes that show up on the body element. This PR adds a couple more.
1. `is_front` or `not_front`
2. `view_{view id}` and `view-display_{view-display}`
To test:
1. Create Sites+ D9 site using this branch for the base theme.
3. Enable some views, create some nodes, set some things to `<front>`.
4. Confirm the correct CSS classes are showing up on the `<body>`. 
For example, if you set the People Directory to front, I'd expect to see:
* `is_front`
* `view_people`
* `view-display_people_directory`
=> D8ISUTHEME-180 Add front and views classes to body

iastate_theme.theme
To test
1. Create a Drupal 9 site with this version of the base theme. (Very okay to make a Sites+ site)
2. If using a Sites+ site, enable Landing Page to get Cards
3. Structure > Blocks > Custom Block Library
4. Create and place different kinds of blocks in theme regions.
5. Create a custom block type and place one in a theme region.
6. Inspect the HTML and confirm that any content blocks have a `block-type_` class. 
7. NOTE: iastate8_cards block types also have their own templates and `isu-` block type classes. This is fine.
8. Confirm the `block-type_` class isn't showing up on, like, view blocks or system blocks.
=> D8ISUTHEME-183 Add block type classes to blocks

css/base.css, css/isu-responsivetables.css, js/isu-responsivetables.js, templates/views/views-view-table.html.twig
This PR does four things:
1. Styles all table elements directly by duplicating Bootstrap 4 styles directly onto `<table>`
2. Creates the `make-responsivle-table` class for making tables in Views and blocks responsive.
3. Cleans up and improves existing table styling.
4. Adds some useful classes on Views tables.
My thought process is here: https://isubit.atlassian.net/browse/D8ISUTHEME-184
**To test**
Create a D9 Sites+ site with this branch of the base theme and make some tables:
Tables in nodes - Make a page or news article (etc) with tables inside. Make tables with no headings, row headings, and column headings. Publish the page. Confirm the tables are styled and responsive. Disable javascript. Confirm the tables are still styled.
Tables in Views - Create or edit a View with a table …
=> D8ISUTHEME-184 Improve responsive tables

css/base.css, css/isu-responsivetables.css
Context: https://isubit.atlassian.net/browse/D8ISUTHEME-186
More context: https://isubit.atlassian.net/browse/D8ISUTHEME-184
This previous table-change had two parts: a) style all tables and b) be able to make non-responsive table responsive.
It turned out that styling all tables was a much bigger hammer than detected in initial testing and was disrupting things like multi-value fields in node forms, other table-drag UI. 
This PR reverts tables back to working as before, but leaves the modification to the responsivetables javascript file that includes the `make-responsive-table` class which are useful in Views or Webforms as an 'opt -in'.
**To test:**
Create a D9 Sites site with this branch of the base theme.
Platform tables that were inadvertently affected last time, but should not be …
=> D8ISUTHEME-186 Revert default table styling
